@apiUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1ODY4OTMwMjEsImV4cCI6MTU4NzQ5NzgyMSwiaWF0IjoxNTg2ODkzMDIxfQ.XAmxeJvH4ABChP6nFfO0Uwak-wh8HR-AxIDRrp1vnLc
###
POST {{apiUrl}}/user/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email" : "bob.test.com",
    "password" : "Pa$$w0rd"
}


###
POST {{apiUrl}}/user/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username" : "Sally1",    
    "displayname" : "Sally1",
    "email" : "Sally1@test.com",
    "password" : "aaaaaaa"
}

###
Get {{apiUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/activities HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{apiUrl}}/Activities HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id" : "{{$guid}}",
    "title" : "Test Create Title",
    "description" : "Descrption for the test event",
    "category" : "agro",
    "date" :"{{$datetime iso8601}}",
    "city" : "London",
    "venue": "tower of london"
}

###
GET {{apiUrl}}/Activities/C0D73AB1-2491-4AA6-9762-497DA95519F8	
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE {{apiUrl}}/Activities/d127a660-ecac-4dd6-9af9-8628c526378a HTTP/1.1
Accept: application/json
Content-Type: application/json


###
PUT {{apiUrl}}/Activities/7ffb3a2e-ca02-4f7e-ad60-ae06d4daff2b HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "id" : "7ffb3a2e-ca02-4f7e-ad60-ae06d4daff2b",
    "title" : "Test Create Title",
    "description" : "Descrption for the test event",
    "category" : "agro",
    "date" :"{{$datetime iso8601}}",
    "city" : "XXX",
    "venue": "XXX"
}


###
POST {{apiUrl}}/user/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email" : "bob.test.com",
    "password" : ""
}


###
POST {{apiUrl}}/user/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email" : "bob.test.com",
    "password" : "xxx"
}