@apiUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1ODY4OTMwMjEsImV4cCI6MTU4NzQ5NzgyMSwiaWF0IjoxNTg2ODkzMDIxfQ.XAmxeJvH4ABChP6nFfO0Uwak-wh8HR-AxIDRrp1vnLc


### Login
POST {{apiUrl}}/user/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email" : "bob.test.com",
    "password" : "Pa$$w0rd"
}
###

### Register
POST {{apiUrl}}/user/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username" : "Sally1",    
    "displayname" : "Sally1",
    "email" : "Sally1@test.com",
    "password" : "aaaaaaa"
}
###

### Get user
GET {{apiUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###


### Get Activities
GET {{apiUrl}}/activities HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Create activity
POST {{apiUrl}}/Activities HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id" : "{{$guid}}",
    "title" : "Test Create Title",
    "description" : "Descrption for the test event",
    "category" : "agro",
    "date" :"{{$datetime iso8601}}",
    "city" : "London",
    "venue": "tower of london"
}
###

### Join activity
POST {{apiUrl}}/Activities/98253cca-67a0-4746-9532-eeac83f9d512/attend
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Leave activity
DELETE  {{apiUrl}}/Activities/ba54699b-f69c-4a1d-92f4-d5b86a9bc5bf/attend
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Get activity
GET {{apiUrl}}/Activities/98253cca-67a0-4746-9532-eeac83f9d512
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Delete activity
DELETE {{apiUrl}}/Activities/d127a660-ecac-4dd6-9af9-8628c526378a HTTP/1.1
Accept: application/json
Content-Type: application/json
###

### Update activity
PUT {{apiUrl}}/Activities/d4768159-3c34-4333-90f7-addc64abfff9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title" : "Test Create Title",
    "description" : "Descrption for the test event",
    "category" : "agro",
    "date" :"{{$datetime iso8601}}",
    "city" : "XXX",
    "venue": "XXX"
}
###


### Login without password
POST {{apiUrl}}/user/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email" : "bob.test.com",
    "password" : ""
}
###

### loging with short password
POST {{apiUrl}}/user/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email" : "bob.test.com",
    "password" : "xxx"
}
###